### ISSUE TITLE
get gid from objects layer

### ISSUE THREAD

**Issue by codetricity** [RafaelBarbosatec/tiled_json_reader#3]
Is there a way to pull the "gid" from the map.json file?  I'm not sure how to get the object to correspond to show the tilemap from my objects layer.  In the map.json below, I have a rock that I want to display.  What's the process it?

map.json
```
         "name":"Object Layer 1",
         "objects":[
                {
                 "gid":632,
                 "height":32,
                 "id":1,
                 "name":"rock",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":166.666666666667,
                 "y":88.6666666666667
                }, 
                {
                 "gid":712,
```

the output from TiledJsonReader.read() does not appear to have the id for the tile.

output from TiledJsonReader.read()
```
objects: [{height: 32.0, id: 1, name: rock, rotation: 0.0, type: , visible: true, width: 32.0, x: 166.666666666667, y: 88.6666666666667},
```

**Comment by RafaelBarbosatec** [comment]
Thanks for report @codetricity !
Available in 1.0.7 version.
